loopSeconds: 3
auth:
  httpsOnly: false
  proxied: false
  ipWhitelisting:
    whitelistExpirySeconds: 86400
    secretKey: KJY4B3ZOFWRNNCN4
  jwt:
    userName: ci
    password: HASH(VyMnzLKdBkOYyYfJqFPzqt/OcKG1+xHtyaObQcmi3bo=)
    passwordSalt: mxnuUXa/SkNmQ+rQ3Qpk3Q==
    secret: 234q9803b21KJHSAD)9832yhSdSUH9222fg234gefdsa11
    secondFactorSecret: O546XLKJMJIQM3PW
    expirationMinutes: 1440
database:
  connectionString: h2:mem:test;DB_CLOSE_DELAY=-1;DEFAULT_LOCK_TIMEOUT=60000
exchanges:
  simulated:
    apiKey: OnlineUser
  gdax-sandbox:
    apiKey:
    secretKey:
    passphrase:
  gdax:
    apiKey:
    secretKey:
    passphrase:
  binance:
    apiKey:
    secretKey:
  kucoin:
    apiKey:
    secretKey:
  cryptopia:
    apiKey:
    secretKey:
  bitfinex:
    apiKey:
    secretKey:
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  maxThreads: 16
logging:
  loggers:
    "com.gruelbox.orko": INFO
    "si.mazi.rescu": ERROR
